import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";
import { siteUrl } from "@/lib/site";
import { SiteFooter } from "@/components/SiteFooter";
import { inquiry, deliverables, timing } from "@/lib/offer";

const faqs = [
  ["Could we do this ourselves?", "Yes. Associations and AI vendors offer useful templates and training. Orpheion is for an agency that wants help choosing where to start, adapting the guidance to its work, testing two workflows and getting staff comfortable using them. If a template is all you need, we’ll say so."],
  ["Who is the setup for?", "One independent insurance agency team of up to 25 people. We review up to ten tools and ten tasks, then agree two workflows to develop. You appoint an operations contact, someone who can approve staff rules, and a licensed reviewer for insurance-related work."],
  ["When will we have something we can use?", timing],
  ["How much time will our team need?", "Plan for a 45-minute kickoff, a 45-minute staff walkthrough and a 30-minute follow-up around day 30. Your contact also gathers answers, checks drafts and tries the workflows. Written alternatives can be agreed. One consolidated revision round per deliverable is included; the follow-up includes one consolidated adjustment to the two agreed workflows."],
  ["Can you help us use ChatGPT to review policies?", "We can develop a workflow to locate policy language and organize questions for your licensed reviewer. The reviewer checks the original documents, including applicable endorsements, and makes the insurance judgments. AI summaries are not coverage decisions. We begin with fictional examples and only use other materials under separately agreed handling terms."],
  ["Where do we send information?", "Use hello@orpheion.com for general questions only. That inbox is connected to AI tools. Confidential intake is currently closed. Start with general descriptions and fictional examples; wait for written approval and separate transfer instructions before sending nonpublic documents."],
  ["What happens after the follow-up?", "You keep the delivered policy and workflow guides for your agency’s internal use. If you want continuing help, we agree the review schedule, response expectations, included work and price separately. There is no automatic renewal or unlimited support commitment."],
  ["What isn’t included?", "Custom software, integrations, third-party subscriptions, client risk reports, continuous monitoring and incident response are outside this setup. This is practical consulting and workflow guidance, not a security audit, legal opinion, coverage determination or guarantee against errors or losses."],
  ["When do we pay?", "After we agree the written scope, confirm readiness and set the dates. The standard setup is $1,500 total. You can cancel before work starts for a full refund. Our service terms explain the remedy if agreed deliverables remain missing. Previously agreed engagements keep their written terms."],
];

export default function Home() {
  return <>
    <a href="#main" className="skip-link">Skip to content</a>
    <SiteHeader/>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
      "@context": "https://schema.org", "@type": "Service", "@id": `${siteUrl}/#agency-ai-setup`,
      name: "Agency AI Setup", serviceType: "AI consulting for independent insurance agencies",
      provider: { "@id": `${siteUrl}/#organization` }, url: `${siteUrl}/#pilot`,
      areaServed: { "@type": "Country", name: "United States" },
      description: "An agency-specific AI-use policy, two tested workflow guides, staff walkthrough and day-30 follow-up. Ten-business-day setup target after agreed start and complete permitted inputs; dates agreed before payment.",
      offers: { "@type": "Offer", price: "1500", priceCurrency: "USD", url: `${siteUrl}/#pilot`, description: "One-time fee for one team of up to 25 people. No automatic renewal. Scope and dates agreed before payment." },
    }).replace(/</g, "\\u003c") }}/>
    <main id="main">
      <section className="risk-hero"><div className="risk-wrap risk-hero-grid"><div>
        <p className="risk-eyebrow">AI consulting for independent insurance agencies</p>
        <h1>Put AI to work.<br/>Give your team a clear way to use it.</h1>
        <p className="risk-lead">You can see the potential. Finding the time to figure it out is another matter. We help your agency set sensible AI rules, get two everyday tasks working, and teach your staff how to check the results.</p>
        <div className="risk-actions"><a className="risk-button" href={inquiry}>Talk with Sam about your agency</a><Link className="risk-text-link" href="/sample">See a practical example</Link></div>
        <p className="risk-caption">$1,500 total · Two-week setup target + day-30 follow-up<br/>Dates agreed before payment. No automatic renewal.</p>
        <p className="risk-caption">Opens your email app. General questions only; please leave confidential details and files out.</p>
      </div><aside className="risk-document risk-hero-report" aria-label="What your team will receive">
        <p className="risk-eyebrow">Something your staff can use at their desks</p><h2>A policy. Two workflows.<br/>A person to walk you through them.</h2>
        <dl><dt>Know what’s allowed</dt><dd>Agency-specific rules for tools, information and human review.</dd><dt>Start with useful work</dt><dd>Two agreed tasks, with prompts, examples and checking steps.</dd><dt>Put it into practice</dt><dd>A staff walkthrough and a scheduled follow-up to work through what needs adjusting.</dd></dl>
        <Link className="risk-text-link" href="/sample#demo">Walk through an email example</Link>
      </aside></div></section>
      <section className="risk-section risk-wrap"><p className="risk-eyebrow">Less guesswork. A useful place to start.</p><h2>You don’t need another pile of AI tips.</h2>
        <p className="risk-lead-small">You need to know what will help your agency—and how your team should use it. We start with the work already on your desks, then build the instructions around your people and tools.</p>
        <div className="risk-three"><article><h3>Draft routine emails.</h3><p>Give staff a repeatable starting point for reminders and follow-ups, with placeholders and checks before anything goes to a client.</p></article><article><h3>Organize policy information.</h3><p>Locate source language and prepare questions for a licensed reviewer. Keep the original documents and human judgment at the center.</p></article><article><h3>Make everyday decisions easier.</h3><p>Agree which tools and uses are allowed, what information stays out, and who to ask when a task falls outside the rules.</p></article></div>
      </section>
      <section id="sample" className="risk-sample"><div className="risk-wrap risk-two"><div><p className="risk-eyebrow">See what you’re buying</p><h2>From “write an email” to a process your team can follow.</h2><p className="risk-lead-small">Explore a sample policy excerpt, a complete email workflow and the checks that catch an unsupported claim. Everything in the example is fictional.</p><Link className="risk-text-link" href="/sample">Open the sample and demonstration</Link><p className="risk-caption">Illustrative materials, not a client result or live AI test.</p></div><div className="risk-document"><p className="risk-eyebrow">A small rule with a practical purpose</p><h3>Draft with placeholders.<br/>Check before sending.</h3><dl><dt>Use AI for</dt><dd>A general reminder with [CLIENT] and [DATE] placeholders.</dd><dt>Keep out</dt><dd>Real client details, policy files and information outside the approved use.</dd><dt>Check</dt><dd>Dates, recipients, tone and any claim about coverage or renewal. Add verified details in the agency’s approved system.</dd></dl></div></div></section>
      <section id="pilot" className="risk-section risk-wrap"><div className="risk-two"><div><p className="risk-eyebrow">Agency AI Setup · delivered by Sam</p><h2>A focused start.<br/><span className="risk-price">$1,500 total.</span></h2><p className="risk-lead-small">One team. Two agreed workflows. A policy that reflects how you work.</p><a className="risk-button" href={inquiry}>Ask about the agency setup</a><p className="risk-caption">We agree scope, participation and dates before payment. Existing written agreements keep their terms.</p></div><div className="risk-offer"><h3>What you receive</h3><ul>{deliverables.map(item=><li key={item}>{item}</li>)}</ul><p className="risk-caption">For one team of up to 25 people. Review of up to ten tools and ten tasks; development of two agreed workflows. Third-party subscriptions are separate.</p></div></div></section>
      <section className="risk-process"><div className="risk-wrap risk-section"><p className="risk-eyebrow">Your first month</p><h2>Start small. Get it working. Follow through.</h2><ol className="risk-steps"><li><h3>01 / Understand the work</h3><p>At kickoff, we choose two tasks, agree what a useful result looks like, and confirm the information and tools staff may use.</p></li><li><h3>02 / Build and check</h3><p>During setup, we draft the policy and workflow guides. We test agreed examples, including cases where the answer should stop or ask for help.</p></li><li><h3>03 / Walk staff through it</h3><p>By the agreed setup date, your team tries the workflows with us. Management approves the rules and reviewers check insurance-related work.</p></li><li><h3>04 / Review actual use</h3><p>Around day 30, we discuss what staff used, time spent reviewing, problems found and the agreed adjustments.</p></li></ol><p className="risk-caption">{timing}</p></div></section>
      <section id="meet-sam" className="risk-section risk-wrap risk-founder"><div className="risk-two"><div><Image src="/sam-bolton.png" alt="Sam Bolton" width={144} height={144} sizes="144px" className="risk-founder-portrait"/><p className="risk-eyebrow">Your point of contact</p><h2>Meet Sam Bolton.</h2><p className="risk-founder-role">Founder, Orpheion · Mount Juliet, Tennessee</p><p className="risk-founder-role">Tennessee P&amp;C producer<br/>ISC2 Certified in Cybersecurity (CC)</p><a className="risk-text-link" href={inquiry}>Email Sam directly</a></div><div className="risk-founder-copy"><p className="risk-lead-small">I’m Sam Bolton, founder of Orpheion, a Tennessee-licensed property and casualty insurance producer, and an ISC2 Certified in Cybersecurity (CC) credential holder.</p><p>My background includes commercial account management and insurance sales. I’ve handled renewals, worked through coverage questions, and helped clients understand their options. I know how much agency work depends on clear communication, careful review, and protecting client information.</p><p>Since ChatGPT’s early days, I’ve used AI extensively in my own work—from research and writing to building working apps, websites, and creative projects. I follow developments in AI tools with particular attention to insurance and cybersecurity. That hands-on experience has taught me where these tools help, where they fall short, and why checking their work matters.</p><p>I built Orpheion to help agencies put AI to work with confidence: choosing worthwhile tasks, establishing clear rules, and giving staff practical workflows they can understand and use.</p><p>You work directly with me. I prepare and review the guidance, lead the walkthrough and handle the agreed follow-up. I use AI to assist with research and drafting, and remain responsible for reviewing what Orpheion delivers.</p><p>Your agency approves its rules and retains responsibility for insurance advice. When a question needs your IT provider, attorney or another specialist, I’ll make that clear.</p></div></div></section>
      <section className="risk-section risk-wrap risk-faq"><p className="risk-eyebrow">Before you decide</p><h2>Good questions to ask.</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}<p className="risk-caption">Read the <Link className="risk-text-link" href="/terms">service terms</Link> and <Link className="risk-text-link" href="/privacy">information-handling notice</Link>.</p></section>
      <section className="risk-close"><div className="risk-wrap"><p className="risk-eyebrow">Orpheion / Practical AI consulting</p><h2>What would you like AI to take off your team’s plate?</h2><p>Tell me about a repetitive task or a question you haven’t had time to work through. We’ll see whether this setup is a useful next step for your agency.</p><a className="risk-button risk-button-light" href={inquiry}>Talk with Sam</a><p className="risk-caption">$1,500 total · No automatic renewal<br/>hello@orpheion.com · General inquiries only. No confidential attachments.</p></div></section>
    </main><SiteFooter/>
  </>;
}
