import Image from "next/image";
import Link from "next/link";
import { OrpheionMark } from "@/components/OrpheionMark";
import { SiteFooter } from "@/components/SiteFooter";
const inquiry = "mailto:hello@orpheion.com?subject=AI%20Risk%20Desk%20questions&body=Hi%20Sam%2C%0A%0AI%27d%20like%20to%20discuss%20whether%20the%20pilot%20fits%20our%20agency.%0AAgency%3A%0AMy%20role%3A%0ATeam%20size%3A%0AOne%20AI%20question%3A%0A";
const sample = "/Orpheion-AI-Risk-Desk-sample.pdf";
const faqs = [
 ["Is this right for our agency?", "The pilot is for one independent commercial insurance team of up to 25 people, using or considering AI. You do not need a finished policy or five participating clients. We confirm your goals, an operations contact and someone authorized to approve staff rules before payment. Insurance-related work requires your licensed producer’s review. If you only need a generic policy template, this service may be more than you need."],
 ["What will we receive, and when?", "Your agency receives an action brief, a draft permitted-use register, a one-page staff guide, three priority actions and two written follow-up reviews. We agree the first delivery date and input deadlines before payment. The pilot lasts 60 days; follow-up reviews occur around day 30 and at close. One correction round per deliverable is included. This is a service, with no software to install."],
 ["How much work will our team need to do?", "We provide the questions and prepare the drafts. Your operations contact supplies descriptions of up to 10 AI tools and 10 tasks, clarifies missing facts and coordinates approval. Meetings total 105 minutes: a 45-minute kickoff, a 30-minute staff walkthrough and a 30-minute closeout. Gathering answers and checking drafts takes additional time. Written meeting alternatives can be agreed. Optional client reports require client responses and producer review."],
 ["Do we need to send confidential client records?", "No client records are needed to begin. Start with workflow descriptions and fictional or redacted examples. Before any confidential information is shared, we agree the permitted data, tools, access and retention in writing. Do not send policy files, claims records, passwords or sensitive personal information in your inquiry."],
 ["Who reviews the work, and what are the limits?", "Sam Bolton coordinates delivery and checks that statements match the supplied information and cited sources. Agency management approves its own rules. Your licensed producer reviews insurance-related and client-facing material. Technical settings, legal questions or incidents that require specialist expertise are referred to your appropriate adviser. This service is not a security audit, legal opinion, coverage determination, implementation service or guarantee against loss. Reviews are scheduled, not continuous monitoring."],
 ["How do payment, optional reports and continuation work?", "The pilot costs $1,500 total, paid after scope, readiness and a start date are agreed. It does not renew automatically. Up to five client AI risk reports and producer notes are included if elected, with complete authorized inputs due by day 30. Each report covers up to five uses. Unused reports expire at day 60, with no rollover or separate refund. Agreed input delays may change dates in writing. You may cancel before work starts for a full refund. Missing core deliverables have a ten-business-day opportunity to complete them after written notice, then a pilot-fee refund on request. Optional continuation is separately agreed at $750/month; see the service terms for its scope."]
];
export default function Home(){return <>
<a href="#main" className="skip-link">Skip to content</a>
<header className="risk-header"><nav className="risk-wrap risk-nav" aria-label="Primary"><Link href="/" className="risk-brand"><OrpheionMark decorative className="h-9 w-9"/><span className="risk-brand-name">Orpheion<span className="risk-brand-service">AI Risk Desk</span></span></Link><div className="risk-nav-links"><a href="#sample">Sample report</a><a href="#pilot">What you get &amp; price</a><a href={inquiry}>Email Sam</a></div></nav></header>
<main id="main">
<section className="risk-hero"><div className="risk-wrap risk-hero-grid"><div><p className="risk-eyebrow">For independent commercial insurance agencies</p><h1>Clear rules for your agency’s AI use.</h1><p className="risk-lead">Your team wants to use AI. You want to know what information they can share and who should check the results. We review your tools and everyday tasks, then give you practical staff rules and three priority actions.</p><div className="risk-actions"><a className="risk-button" href={inquiry}>Discuss the $1,500 pilot</a><a className="risk-text-link" href={sample}>See the sample</a></div><p className="risk-caption">$1,500 total · 60 days · No automatic renewal<br/>Opens your email app. Or write to <a href="mailto:hello@orpheion.com">hello@orpheion.com</a>.<br/>Please leave confidential client information out of your inquiry.</p></div><aside className="risk-document risk-hero-report" aria-label="Fictional agency decision example"><p className="risk-eyebrow">A useful answer to “Can I use AI for this?”</p><h2>Draft the email.<br/>Keep client details out.</h2><p className="risk-caption">Fictional example · Not a customer result</p><dl><dt>The task</dt><dd>Draft a general renewal reminder using fictional placeholders.</dd><dt>The proposed rule</dt><dd>Use an agency-approved account. Add client details outside the AI tool. A person checks facts and recipients before sending.</dd><dt>The decision belongs to</dt><dd>Your operations lead, after reviewing the tool and the proposed use.</dd></dl><a className="risk-text-link" href={sample}>See a complete agency action brief</a></aside></div></section>
<section className="risk-section risk-wrap"><p className="risk-eyebrow">Practical help, with follow-through</p><h2>You shouldn’t have to figure out AI alone.</h2><p className="risk-lead-small">Give your staff a clear answer when they ask what they can use, what information stays out and when someone needs to check the work.</p><div className="risk-three"><article><h3>Rules your staff can use.</h3><p>A one-page staff guide and draft permitted-use register connect each task to its data limits and review requirements. Your management approves the rules.</p></article><article><h3>Three actions to tackle first.</h3><p>A short agency action brief identifies priorities, proposed owners and the evidence needed to close each issue.</p></article><article><h3>Two follow-up reviews.</h3><p>At around day 30 and at close, we review the agreed sources and outstanding actions. You receive a written update, including what remains unresolved.</p></article></div></section>
<section id="sample" className="risk-sample"><div className="risk-wrap risk-two"><div><p className="risk-eyebrow">See the work before you decide</p><h2>From an uncertain answer to a documented decision.</h2><p className="risk-lead-small">Our sample separates what an agency reported, what has been checked and what still needs evidence. Each recommendation has a proposed owner and next step.</p><a className="risk-text-link" href={sample}>Read the sample · PDF</a><p className="risk-caption">Six pages: agency action brief, staff guidance, optional client report, producer notes and pilot scope. All examples are fictional.</p></div><div className="risk-document"><p className="risk-eyebrow">An example from the agency review</p><h3>Confidential uploads need a decision.</h3><dl><dt>Reported</dt><dd>A staff member used a personal chatbot with client information.</dd><dt>Still unverified</dt><dd>What was shared, which account was used and what its settings permit.</dd><dt>Proposed next step</dt><dd>Pause confidential uploads and ask the agency’s IT contact to review the account. Record management’s decision and permitted uses.</dd></dl></div></div></section>
<section id="pilot" className="risk-section risk-wrap"><div className="risk-two"><div><p className="risk-eyebrow">The 60-day paid pilot</p><h2>A clear plan for your agency.<br/><span className="risk-price">$1,500 total.</span></h2><p className="risk-lead-small">For one team of up to 25 people. Start with your own agency; client participation is optional.</p><a className="risk-button" href={inquiry}>Discuss the $1,500 pilot</a><p className="risk-caption">Scope, delivery dates and readiness agreed before payment. No automatic renewal.</p></div><div className="risk-offer"><h3>Included in your pilot</h3><ul><li>Review of up to 10 AI tools and 10 everyday tasks.</li><li>Agency action brief, draft permitted-use register, one-page staff guide and three priority actions.</li><li>Two written follow-up reviews, around day 30 and at close.</li><li>A 45-minute kickoff, 30-minute staff walkthrough and 30-minute closeout. One correction round per deliverable.</li><li>Up to five optional client AI risk reports with producer notes, under the participation terms below.</li></ul></div></div></section>
<section className="risk-process"><div className="risk-wrap risk-section"><p className="risk-eyebrow">How the work moves forward</p><h2>Understand. Decide. Follow through.</h2><ol className="risk-three"><li><h3>01 / Describe the work</h3><p>We provide a short questionnaire. Your operations contact tells us which tools are used, for what tasks and with what information. We agree input and delivery dates before payment.</p></li><li><h3>02 / Review a practical plan</h3><p>We check the supplied descriptions and named sources, distinguish unknowns from evidence, and draft the guide and actions. Your team checks facts and approves its rules.</p></li><li><h3>03 / Check progress</h3><p>We walk your team through the materials and revisit the agreed issues at two scheduled reviews. You decide what to implement and whether any further work is worthwhile.</p></li></ol></div></section>
<section className="risk-section risk-wrap"><p className="risk-eyebrow">How we review an AI use</p><h2>Every recommendation should have a reason.</h2><p className="risk-lead-small">We record the task, the information involved, the tool and account type, the evidence source and date, and who needs to make the decision.</p><div className="risk-three"><article><h3>Reported.</h3><p>Information supplied by your team is identified as reported. A questionnaire answer is not proof that a setting or control works.</p></article><article><h3>Supported by evidence.</h3><p>We cite the document or vendor guidance reviewed and its date. Reviewing documentation is not independent technical testing.</p></article><article><h3>Still needs checking.</h3><p>Missing or contradictory facts stay visible. Questions needing legal, security or insurance expertise go to your appropriate adviser.</p></article></div></section>
<section id="meet-sam" className="risk-section risk-wrap risk-founder"><div className="risk-two"><div><Image src="/sam-bolton.png" alt="Sam Bolton" width={144} height={144} sizes="144px" className="risk-founder-portrait"/><p className="risk-eyebrow">Your point of contact</p><h2>Meet Sam Bolton.</h2><p className="risk-founder-role">Owner, Orpheion</p><a className="risk-text-link" href={inquiry}>Email Sam directly</a></div><div className="risk-founder-copy"><p className="risk-lead-small">I run Orpheion and coordinate your pilot from the first questions to the final review.</p><p>I check that our deliverables reflect the information provided, identify their sources and make unresolved questions clear. We use AI to assist with research and drafting.</p><p>Your management approves agency rules. Your licensed producer reviews insurance-related and client-facing material. Where a question needs technical or legal expertise, we identify it for your appropriate adviser; that specialist work is outside this pilot.</p></div></div></section>
<section className="risk-sample"><div className="risk-wrap risk-two"><div><p className="risk-eyebrow">Optional client phase · included in the price</p><h2>Bring the same questions to your clients.</h2><p className="risk-lead-small">When your agency is ready, use the pilot with up to five commercial clients. Each gets a two-page AI risk report with your logo, plus separate notes for your producer.</p><a className="risk-text-link" href={sample}>See a fictional client report</a></div><div><h3>Choose it when it fits your team.</h3><p>You select willing clients and coordinate their responses. Elect the reports and provide complete, authorized inputs by day 30. Each report covers up to five AI uses and requires licensed producer review before client distribution.</p><p>Unused reports expire at day 60, with no rollover or separate refund. Any deadline extension must be agreed in writing. You do not need participating clients to start the agency review.</p></div></div></section>
<section className="risk-section risk-wrap risk-faq"><p className="risk-eyebrow">Questions before you buy</p><h2>What to expect.</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}<p className="risk-caption">Read the <Link href="/terms" className="risk-text-link">service terms</Link> and <Link href="/privacy" className="risk-text-link">information-handling notice</Link>.</p></section>
<section className="risk-close"><div className="risk-wrap"><p className="risk-eyebrow">Orpheion / AI Risk Desk</p><h2>Start with the question your team is asking.</h2><p>Tell Sam which AI tool or task you are working through. We’ll discuss whether the pilot fits before you commit.</p><a className="risk-button risk-button-light" href={inquiry}>Discuss the $1,500 pilot</a><p className="risk-caption">Opens your email app. Or write to hello@orpheion.com.<br/>Please leave confidential client information out of your inquiry.</p></div></section>
</main><SiteFooter/></>}
