import type { Metadata } from "next";
import { LegalShell } from "@/components/LegalShell";
export const metadata: Metadata = {title: "Service terms | Orpheion AI Risk Desk", alternates: {canonical: "/terms"}};
export default function Terms(){return <LegalShell title="AI Risk Desk service terms" updated="September 13, 2026">
<section><h2>1. Agree on the engagement before starting</h2><p>Orpheion provides AI-use documentation, proposed control actions and client exposure discussion materials for independent insurance agencies. Contact hello@orpheion.com to confirm fit. An engagement begins only after the parties identify the contracting provider and agency, agree a written scope and start date, and confirm payment. Browsing this site or sending an inquiry does not purchase a service. The signed engagement controls if it differs from this summary.</p></section>
<section><h2>2. Pilot scope and price</h2><p>The pilot is $1,500 total for 60 days, for one team of up to 25 staff. It covers up to ten AI tools and ten workflows, an agency action brief, draft permitted-use register and one-page staff guide, three priority control recommendations, up to five optional two-page client reports with producer notes, two scheduled written reviews around day 30 and at close, and one correction round per deliverable. Each snapshot covers up to five AI uses. A 45-minute kickoff, 30-minute staff walkthrough and 30-minute closeout are included. Written delivery is available by agreement: a kickoff questionnaire and one clarification round, an annotated guide and one consolidated Q&A, and a written closeout and one Q&A. These replace the three meetings; they do not add unlimited email consulting. We target the first draft within ten business days after the agreed start and receipt of complete permitted inputs. We confirm the actual deadline before payment; input delays require agreed date changes. Client participation is not required to start. To use the included client reports, elect them and provide complete authorized inputs by day 30. Unused reports expire at day 60, with no rollover or separate refund. Agreed extensions must be in writing. Additional work requires written agreement on price and timing.</p></section>
<section><h2>3. Your participation and review</h2><p>The agency appoints an authorized sponsor and operations owner. Insurance-related or client-facing work also requires a licensed producer reviewer. It supplies accurate, authorized information and confirms client permission where needed. Client-facing materials require agency approval before use. Input deadlines and review dates are agreed in writing; client delays or scope changes may change delivery dates by written agreement.</p></section>
<section><h2>4. Service boundaries</h2><p>Materials identify reported uses, evidence gaps and proposed actions. They are not legal opinions, coverage determinations, compliance certifications, security audits or guarantees of loss prevention. Orpheion does not bind, place or sell insurance through this service. Licensed producers retain responsibility for insurance advice; appropriate legal and security specialists handle matters within their expertise. Software implementation, incident response and continuous monitoring are excluded.</p></section>
<section><h2>5. Payment and delivery remedy</h2><p>The pilot fee is paid upfront after scope and delivery readiness are agreed. The agency may cancel before work starts for a full refund. If Orpheion cannot start on the agreed date, the agency may request a refund before work begins. Core deliverables include the agency materials and any client reports elected with complete authorized inputs by day 30. If core deliverables remain missing at day 60, the agency may notify Orpheion and allow ten business days to complete them, then request a pilot-fee refund if they are still missing. Agreed extensions for input delays and scope changes are recorded in writing. Refund requests go to hello@orpheion.com.</p></section>
<section><h2>6. Optional continuation</h2><p>The pilot does not renew automatically. A separately accepted $750/month service includes the maintained scoped register, monthly action and monitoring brief, two new or refreshed client snapshots each month, quarterly control refresh and a 30-minute monthly review. Unused snapshots do not roll over. Continuation is month-to-month and billed in advance; cancel before the next billing date to stop future billing. Any mid-period refund terms must be stated in the continuation agreement.</p></section>
<section><h2>7. Confidential information and permitted use</h2><p>Confidential intake is currently closed. Do not send confidential agency or client information in an initial inquiry. Before receiving such material, the parties agree permitted uses, transfer method, access, retention, deletion and any approved AI processing. Only minimum necessary information should be supplied. Orpheion may use AI-assisted drafting under the agreed processing terms; a human must check the final deliverables. The agency may brand and use paid deliverables for the named clients, subject to review. General templates remain reusable; confidential client information is not part of those reusable templates.</p></section>
<section><h2>8. Questions and final agreement</h2><p>Contact hello@orpheion.com. The signed engagement must identify the legal parties, applicable commercial terms and agreed data handling before work starts. These service descriptions do not establish that a particular agency has qualified or that delivery capacity has been reserved.</p></section>
</LegalShell>}
