import { pageMetadata } from "@/lib/site";
import { LegalShell } from "@/components/LegalShell";
import { deliverables, timing } from "@/lib/offer";
export const metadata = pageMetadata("Agency AI Setup: Scope & Service Terms | Orpheion", "Read the scope, $1,500 fee, setup timing, review responsibilities and cancellation terms for Orpheion Agency AI Setup.", "/terms");
export default function Terms(){return <LegalShell title="Agency AI Setup service terms" updated="September 19, 2026">
<section><h2>1. Agree on the engagement before starting</h2><p>Orpheion provides practical AI consulting, agency AI-use documentation and guided workflow setup. An engagement begins only after the parties identify the contracting provider and agency, agree a written scope and start date, and confirm payment. Browsing this site or sending an inquiry does not purchase a service. These terms describe new offers from September 19, 2026. Previously agreed engagements retain their written terms; this update does not shorten or remove previously agreed services. The signed engagement controls if it differs from this summary.</p></section>
<section><h2>2. Setup scope and price</h2><p>The standard fee is $1,500 total for one team of up to 25 people. We review up to ten tools and ten tasks and develop two agreed workflows. The setup includes:</p><ul>{deliverables.map(item=><li key={item}>{item}</li>)}</ul><p>{timing} Written meeting alternatives require agreement: a kickoff questionnaire and one clarification round, an annotated staff guide and one consolidated Q&amp;A, and a written day-30 review with one consolidated Q&amp;A. These replace meetings. They do not add unlimited email support.</p></section>
<section><h2>3. Your participation and acceptance</h2><p>The agency appoints an authorized sponsor and operations contact, and a licensed reviewer for insurance-related work. It supplies accurate, authorized information, checks drafts and approves staff rules. Before starting, we agree the two tasks, examples and acceptance criteria. Setup handover includes management review of the policy, documented workflow checks including failure cases, and a staff walkthrough or agreed written alternative. Tests support a limited pilot; they do not certify accuracy in every situation. Input delays and changes to tasks or dates require written agreement.</p></section>
<section><h2>4. Service boundaries</h2><p>The setup develops instructions, prompts and review procedures in the agreed tools. It does not include custom software, integrations, third-party subscriptions, client risk reports, incident response or continuous monitoring. Materials are not legal opinions, coverage determinations, compliance certifications, security audits or guarantees against loss. Orpheion does not bind, place or sell insurance through this service. The agency retains responsibility for insurance advice and operating decisions; appropriate specialists handle legal, technical and security matters outside this scope.</p></section>
<section><h2>5. Payment and delivery remedy</h2><p>The fee is paid upfront after scope, readiness and dates are agreed. The agency may cancel before work starts for a full refund. If Orpheion cannot start on the agreed date, the agency may request a refund before work begins. Core deliverables are the setup materials, walkthrough or written alternative, and agreed day-30 review and adjustment. If a core deliverable remains missing after its agreed due date, the agency may give written notice and allow ten business days for completion, then request a setup-fee refund if it remains missing. Extensions for agency delays or scope changes must be recorded in writing. Requests go to hello@orpheion.com.</p></section>
<section><h2>6. Continuing help</h2><p>There is no automatic renewal. Any ongoing advisory work requires a separate written scope, price, review frequency, response expectations and cancellation terms. No recurring fee or unlimited availability is included or authorized by this setup.</p></section>
<section><h2>7. Information handling and use of materials</h2><p>Confidential intake is currently closed. Initial inquiries must not contain confidential agency or client information. We begin with general descriptions and fictional examples. Any subsequent confidential transfer requires separately agreed permitted data, transfer method, access, retention, deletion and approved processing. No AI processing of confidential material is authorized by default. Orpheion may use AI-assisted research and drafting with permitted information; Sam reviews the deliverables. The agency may use and adapt paid materials internally. General templates remain reusable, without confidential agency information.</p></section>
<section><h2>8. Questions and final agreement</h2><p>Contact hello@orpheion.com. The signed engagement identifies the legal parties, final commercial terms and information-handling arrangements. The website does not reserve delivery capacity or establish that an agency is ready to start.</p></section>
</LegalShell>}
