import type { Metadata } from "next";
import { LegalShell } from "@/components/LegalShell";
export const metadata: Metadata = {title: "Privacy | Orpheion", alternates: {canonical: "/privacy"}};
export default function Privacy(){return <LegalShell title="Privacy and information handling" updated="September 19, 2026">
<section><h2>Contact and scope</h2><p>Contact Orpheion at hello@orpheion.com with privacy questions or requests. This notice describes the website and inquiry process. Processing of agency or insured information for a paid engagement must be agreed separately before transfer.</p></section>
<section><h2>Website and inquiries</h2><p>This website provides service information and links that open your email application. It does not contain a client-record upload form. If you email us, we receive the name, email address, message and attachments you choose to send. We use inquiry information to respond, discuss fit and maintain the related business correspondence. Please do not include confidential agency or client information, or sensitive personal information in an initial inquiry.</p></section>
<section><h2>Service providers</h2><p>Business correspondence uses Google Workspace. We have connected OpenAI tools to assist with reviewing inquiries and drafting replies. Confidential intake is currently closed. Do not send confidential agency or client information to this inbox. The website is configured for Vercel hosting; hosting infrastructure may process technical request information such as IP addresses, browser information and access logs. If you become a customer, Stripe may process your payment through a separately provided invoice or checkout. Payment card details should never be sent to us by email. Each provider&apos;s handling is subject to its applicable terms and privacy information.</p></section>
<section><h2>How document intake works</h2><p>Use hello@orpheion.com for questions, introductions and general business correspondence. That inbox is connected to OpenAI tools. We are preparing a separate intake account and restricted folders for approved engagement materials; confidential intake is not yet open. Wait for written confirmation from Sam and instructions for your specific engagement before sending any nonpublic information. An email address, payment or folder link alone is not an invitation to upload.</p><p>Before intake opens for an engagement, we agree what information is needed, who may access it, how it will be handled and when working copies will be removed. Please do not send passwords, payment card details, claims files or other client records unless the specific information has been expressly agreed as necessary and an approved transfer method has been provided.</p></section>
<section><h2>AI-assisted work and client information</h2><p>Orpheion uses AI-assisted research and drafting with public information and fictional examples. No AI tool is currently approved for confidential engagement inputs. Any future use would require a specifically approved service and account, agreed information-handling controls and written customer authorization. An initial inquiry is not permission to process client records in AI tools.</p></section>
<section><h2>Retention and requests</h2><p>We retain correspondence needed to handle inquiries and ongoing business records. Engagement-specific retention and deletion periods must be agreed before client information is received. You may request access, correction or deletion of information you supplied by emailing hello@orpheion.com. We will assess the request, verify identity where appropriate and explain any records that must be retained for contractual or applicable legal obligations.</p></section>
<section><h2>Website tracking and changes</h2><p>The current site code does not add advertising trackers, analytics scripts or an account login. Hosting and communications providers may still process technical data. This notice will be updated when the service or information-handling process changes.</p></section>
</LegalShell>}
