import type { Metadata } from "next";
import { LegalShell } from "@/components/LegalShell";
export const metadata: Metadata = {title: "Privacy | Orpheion AI Risk Desk", alternates: {canonical: "/privacy"}};
export default function Privacy(){return <LegalShell title="Privacy and information handling" updated="September 11, 2026">
<section><h2>Contact and scope</h2><p>Contact Orpheion at hello@orpheion.com with privacy questions or requests. This notice describes the website and inquiry process. Processing of agency or insured information for a paid engagement must be agreed separately before transfer.</p></section>
<section><h2>Website and inquiries</h2><p>This website provides service information and links that open your email application. It does not contain a client-record upload form. If you email us, we receive the name, email address, message and attachments you choose to send. We use inquiry information to respond, discuss fit and maintain the related business correspondence. Please do not include confidential client records or sensitive personal information in an initial inquiry.</p></section>
<section><h2>Service providers</h2><p>Business correspondence uses Google Workspace. The website is configured for Vercel hosting; hosting infrastructure may process technical request information such as IP addresses, browser information and access logs. If you become a customer, Stripe may process your payment through a separately provided invoice or checkout. Payment card details should never be sent to us by email. Each provider&apos;s handling is subject to its applicable terms and privacy information.</p></section>
<section><h2>AI-assisted work and client information</h2><p>AI Risk Desk may use AI-assisted research and drafting. Before any confidential agency or client data is used in that process, the engagement must specify approved tools, permitted information, access controls and retention. An initial inquiry is not permission to process your client records in AI tools. Information should be minimized and de-identified where practical.</p></section>
<section><h2>Retention and requests</h2><p>We retain correspondence needed to handle inquiries and ongoing business records. Engagement-specific retention and deletion periods must be agreed before client information is received. You may request access, correction or deletion of information you supplied by emailing hello@orpheion.com. We will assess the request, verify identity where appropriate and explain any records that must be retained for contractual or applicable legal obligations.</p></section>
<section><h2>Website tracking and changes</h2><p>The current site code does not add advertising trackers, analytics scripts or an account login. Hosting and communications providers may still process technical data. This notice will be updated when the service or information-handling process changes.</p></section>
</LegalShell>}
